[package]
name = "joinproxy_lib"
version = "1.0.0"
description = "Utilities to use IC together with Joining Proxy"
repository = "https://github.com/vporton/joining-proxy-rust"
keywords = [
  "proxy",
  "HTTP",
  "outcalls",
  "IC",
  "ICP",
  "Internet",
  "Computer"
]
license = "MIT"

[dependencies]
itertools = "0.2.1"
sha2 = "0.0.6"
stableheapbtreemap = "1.5.0"
xtended-numbers = "0.2.1"